### ISSUE TITLE
Add Folder Error

### ISSUE THREAD

**Issue by shan199105** [deanishe/alfred-fuzzyfolders#6]
When I use file action to add a folder or init a search, it has the following error:
```
[2016-05-19 21:09:07][ERROR: action.script] 21:09:07 ff.py:974 DEBUG    wf.args : [u'add', u'/Users/tshan/repo']
21:09:07 ff.py:975 DEBUG    args : {u'<dir>': u'/Users/tshan/repo',
 u'<profile>': None,
 u'<query>': None,
 u'add': True,
 u'alfred-browse': False,
 u'alfred-search': False,
 u'choose': False,
 u'keyword': False,
 u'load-profile': False,
 u'load-settings': False,
 u'manage': False,
 u'open-help': False,
 u'remove': False,
 u'search': False,
 u'settings': False,
 u'update': False,
 u'update-setting': False}
21:09:07 ff.py:310 DEBUG    dirpath : u'/Users/tshan/repo'  query : None
21:09:07 ff.py:160 DEBUG    calling Alfred with : u'tell application "Alfred 2" to search ":fzykey ~/repo \u27a3 "'
31:39: syntax error: A “"” can’t go after this identifier. (-2740)
```

**Comment by shan199105** [comment]
when I type fuzzy and enter on setting, it has the following error as well

[2016-05-19 15:03:48][ERROR: action.script] 15:03:48 ff.py:974 DEBUG    wf.args : [u'load-settings', u'0']
15:03:48 ff.py:975 DEBUG    args : {u'<dir>': None,
 u'<profile>': u'0',
 u'<query>': None,
 u'add': False,
 u'alfred-browse': False,
 u'alfred-search': False,
 u'choose': False,
 u'keyword': False,
 u'load-profile': False,
 u'load-settings': True,
 u'manage': False,
 u'open-help': False,
 u'remove': False,
 u'search': False,
 u'settings': False,
 u'update': False,
 u'update-setting': False}
15:03:48 ff.py:310 DEBUG    dirpath : None  query : None
15:03:48 ff.py:160 DEBUG    calling Alfred with : u'tell application "Alfred 2" to search ":fzyset 0"'
31:39: syntax error: A “"” can’t go after this identifier. (-2740)

**Comment by shan199105** [comment]
Using Alfred v3, OS X 10.11.4

**Comment by deanishe** [comment]
Could you paste the log from the log file in code tags?

**Comment by shan199105** [comment]
Updated

**Comment by deanishe** [comment]
This workflow isn't compatible with Alfred 3 yet. At the very least, you'll need to change calls to `Alfred 2`, such as [here](https://github.com/deanishe/alfred-fuzzyfolders/blob/master/src/ff.py#L105).

I haven't yet familiarised myself with Alfred 3's info.plist. If that's changed significantly, the workflow will *break itself* in Alfred 3.

**Comment by shan199105** [comment]
Thanks for the advice.
