### ISSUE TITLE
alfred3 compatibility

### ISSUE THREAD

**Issue by anandsunku** [deanishe/alfred-fuzzyfolders#7]
i just now bought the alfred3 with powerpack, even after following the instructions as per your website, it is not working. is it compatible with alfred 3?

how to make it compatible

**Comment by deanishe** [comment]
Added in [version 2.3](https://github.com/deanishe/alfred-fuzzyfolders/releases/tag/v2.3).

In future, please do not spam me with email and the Alfred forum with threads. A GitHub issue is quite sufficient.
