### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by jackblackevo** [deanishe/alfred-fuzzyfolders#8]
Hello!
When I use Fuzzy Folders, it always cause very high CPU usage.
I am using Alfred 3.4, macOS 10.12.5.

**Comment by deanishe** [comment]
Run [this workflow](https://github.com/deanishe/alfred-fixum) and see if the problem persists.

**Comment by jackblackevo** [comment]
Thank you! Alfred Fixum fixed this problem.
Will Fuzzy Folders to release new version to fix this without Alfred Fixum?

**Comment by deanishe** [comment]
At some point, yes.

If I update any of my older workflows using Alfred 3, it breaks backwards-compatibility with Alfred 2, which is something I don't like to do unless I also have new features to add.

You should keep Fixum around. Many workflows that are no longer updated are affected by the bug, so it's quite likely you'll run into the issue again when you install a "new" workflow.

An upcoming version of Alfred can recognise and disable affected workflows. Fixum is the simplest way to get them working again.
